FROM registry.access.redhat.com/ubi9/go-toolset:1.26.4 AS builder

USER root

WORKDIR /app

COPY . .

RUN go build ./...

RUN go test ./... -race

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -extldflags=-static" -o prometheus-cardinality-exporter .

FROM registry.access.redhat.com/ubi9-micro@sha256:b498b3ea26111ab4b81d65139f2ebd2ef9a2abb7a4588b7fdcc54889f95e9caa

EXPOSE 9090

COPY --from=builder /app/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

USER 65532

LABEL name="prometheus-cardinality-exporter" \
      description="Exports Prometheus TSDB cardinality statistics as metrics" \
      com.redhat.component="prometheus-cardinality-exporter" \
      io.k8s.description="Exports Prometheus TSDB cardinality statistics as metrics" \
      io.k8s.display-name="Prometheus Cardinality Exporter" \
      summary="Prometheus cardinality exporter for Konflux observability" \
      maintainer="konflux-o11y <konflux-o11y@redhat.com>" \
      url="https://github.com/kubasikus/prometheus-cardinality-exporter" \
      vendor="Red Hat" \
      version="0.1" \
      release="1" \
      distribution-scope="public"

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
