# 1.26.2-alpine3.23 (linux/amd64)
FROM golang:1.26.4-alpine3.23@sha256:18b460dd17542c2ba43299a633cf6ebfc1115101509531471d7cfce1019af083 AS builder

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /app

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" -o prometheus-cardinality-exporter .

FROM scratch

EXPOSE 9090

COPY --from=builder /app/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

USER 255999

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
